### ISSUE TITLE
fix: `cni=auto` does not work when `nodes>=2` with `docker`, `qemu2`, `kvm2` drivers

### ISSUE THREAD

**Issue by caerulescens** [scott-the-programmer/terraform-provider-minikube#131]
# description

The error; I added "`<service_name>`" as a placeholder:
```text
"transport: Error while dialing: dial tcp: lookup <service_name>: i/o timeout"
```

There seems to be an issue with the way that `terraform-provider-minikube` is configuring the CNI plugin when there's multiple nodes. I have been using the `kvm2`, `qemu2`, and `docker` drivers; my issue doesn't occur with `minikube start --driver=<driver_name> --nodes=3` usage with the exception of `driver=qemu2` and `network=builtin`, which doesn't work upstream (see below).

The main issue seems to be that containers cannot communicate after I install a `helm` chart where one pod communicates with another pod. I've identified that the containers can always communicate using `minikube start --driver=<driver_name> --nodes=3`, and they can never communicate when using `terraform-minikube-provider` with `--cni=auto`. When using `terraform-provider-minikube` with the `kvm2` driver, `kindnet` does start correctly, and the `coredns` records look correct too. 

I've attached isolated audit logs for successful single and multi-node `minikube start` runs with `docker` and `kvm2` drivers.

### `minikube`

```
$ minikube version
minikube version: v1.32.0
commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d
```

### `docker`

```
$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### os

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

### libvirt

```
$ virsh version 
Compiled against library: libvirt 9.0.0
Using library: libvirt 9.0.0
Using API: QEMU 9.0.0
Running hypervisor: QEMU 7.2.7
```

## Cases causing the issue

To be clear, `nodes=1` always works for `minikube start` usage and `terraform-provider-minikube` usage.

### Configure `driver=docker` + `nodes=3` + `cni=auto`

Logs from `minikube start` usage:
[logs-docker-single-node-success.txt](https://github.com/scott-the-programmer/terraform-provider-minikube/files/14120010/logs-docker-single-node-success.txt)
[logs-docker-multi-node-success.txt](https://github.com/scott-the-programmer/terraform-provider-minikube/files/14119991/logs-docker-multi-node-success.txt)

```terraform
resource "minikube_cluster" "default" {
  cluster_name        = "minikube"
  driver              = "docker"
  nodes               = 3
  cni                 = "auto"
}
```

### Configure `driver=kvm2` + `nodes=3` + `cni=auto`

Logs from `minikube start` usage:
[logs-kvm2-single-node-success.txt](https://github.com/scott-the-programmer/terraform-provider-minikube/files/14120045/logs-kvm2-single-node-success.txt)
[logs-kvm2-multi-node-success.txt](https://github.com/scott-the-programmer/terraform-provider-minikube/files/14120080/logs-kvm2-multi-node-success.txt)

```terraform
resource "minikube_cluster" "default" {
  cluster_name        = "minikube"
  driver              = "kvm2"
  nodes               = 3
  cni                 = "auto"
}
```

### Configure `driver=qemu2` + `nodes=3` + `cni=auto` + `network=builtin`

This doesn't seem to work upstream either, so I'm not concerned with this case:
* https://github.com/kubernetes/minikube/issues/18067

```terraform
resource "minikube_cluster" "default" {
  cluster_name        = "minikube"
  driver              = "kvm2"
  nodes               = 3
  cni                 = "auto"
  network             = "builtin"
}
```

**Comment by caerulescens** [comment]
Not really sure how to describe this bug, but it doesn't happen upstream in `minikube` like I mentioned.

**Comment by sgardnerdell** [comment]
I've encountered the same issue using the docker driver.  
I used `minikube profile list -o json | jq` to compare the configuration for a minikube provisioned cluster and one provisioned by the terraform provider and tried to align the two as far as possible (adding container_runtime = "docker" and network_plugin = "cni" resolved a few things), however the minikube provisioned cluster reports `"MultiNodeRequested": true` whereas the terraform provisioned cluster reports "MultiNodeRequested": false - could be unrelated but thought I'd mention it.

**Comment by caerulescens** [comment]
@io-timeout I followed that line of reasoning in a similar way, but by using the `ClusterConfiguration` in the logs:

```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.49.2
  bindPort: 8443
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
  name: "minikube"
  kubeletExtraArgs:
    node-ip: 192.168.49.2
  taints: []
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  certSANs: ["127.0.0.1", "localhost", "192.168.49.2"]
  extraArgs:
    enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    leader-elect: "false"
scheduler:
  extraArgs:
    leader-elect: "false"
certificatesDir: /var/lib/minikube/certs
clusterName: mk
controlPlaneEndpoint: control-plane.minikube.internal:8443
etcd:
  local:
    dataDir: /var/lib/minikube/etcd
    extraArgs:
      proxy-refresh-interval: "70000"
kubernetesVersion: v1.28.3
networking:
  dnsDomain: cluster.local
  podSubnet: "10.244.0.0/16"
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  x509:
    clientCAFile: /var/lib/minikube/certs/ca.crt
cgroupDriver: systemd
hairpinMode: hairpin-veth
runtimeRequestTimeout: 15m
clusterDomain: "cluster.local"
# disable disk resource management by default
imageGCHighThresholdPercent: 100
evictionHard:
  nodefs.available: "0%!"(MISSING)
  nodefs.inodesFree: "0%!"(MISSING)
  imagefs.available: "0%!"(MISSING)
failSwapOn: false
staticPodPath: /etc/kubernetes/manifests
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clusterCIDR: "10.244.0.0/16"
metricsBindAddress: 0.0.0.0:10249
conntrack:
  maxPerCore: 0
# Skip setting "net.netfilter.nf_conntrack_tcp_timeout_established"
  tcpEstablishedTimeout: 0s
# Skip setting "net.netfilter.nf_conntrack_tcp_timeout_close"
  tcpCloseWaitTimeout: 0s
```

It's related to `kubelet` so I think it's something related to how `kubeadm` initializes the node communication, but I'm not sure.

---

@scott-the-programmer Another thing to note is that when `driver=kvm2` and `node=1`, then `minikube` selects `cni=bridge` by default. When `driver=kvm2` and `nodes>=2`, then `minikube` defaults to using `kindnet`. If you start the cluster with `minikube start --driver=kvm2 --nodes=2 --cni=bridge` on linux, then there's an intentional exit where the developers raise this info. Their seems to be some special logic that `minikube` defaults to when using `kvm2` and `nodes>=2`. The logic doesn't run when `nodes=1`.
